### PR TITLE
Bump Ruby to 2.6.3

### PR DESCRIPTION
**Pull request by magneland**

### CODE REVIEW

**Comment by magneland** [comment]
I had to redo this PR many times to make CI go green :-(
I am unsure if the manifest file actually makes sense.
Maybe it should follow this pattern instead?
https://github.com/appfolio/academy_app/blob/e18344900e63b2ce9a6e542c577221e2d554c092/app/assets/config/manifest.js

**Comment by sarahsehr** [comment]
> I had to redo this PR many times to make CI go green :-(
> I am unsure if the manifest file actually makes sense.
> Maybe it should follow this pattern instead?
> https://github.com/appfolio/academy_app/blob/e18344900e63b2ce9a6e542c577221e2d554c092/app/assets/config/manifest.js

i tried to remove coffeescript and it caused an issue with deploying so I faked its existing by defining some modules in `lib`.  I hope that's not contributing to this problem.  :(

**Comment by magneland** [comment]
> > I had to redo this PR many times to make CI go green :-(
> > I am unsure if the manifest file actually makes sense.
> > Maybe it should follow this pattern instead?
> > https://github.com/appfolio/academy_app/blob/e18344900e63b2ce9a6e542c577221e2d554c092/app/assets/config/manifest.js
> 
> i tried to remove coffeescript and it caused an issue with deploying so I faked its existing by defining some modules in `lib`. I hope that's not contributing to this problem. :(

I don't know. It's probably fine to have some dummy files in this app

**Comment by sarahsehr** [comment]
Regression tested webhook and PR pull functionality.  Blanked on user setup, so didn't test that :D

**Pull request merged**
